<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace OAG\BlogUrlRewrite\Model;
use Magento\Store\Model\StoreManagerInterface;
use OAG\BlogUrlRewrite\Model\PostUrlPathGenerator;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use Magento\Store\Model\Store;
use OAG\Blog\Api\Data\PostInterface;

class PostUrlRewriteGenerator
{
    /**
     * Entity type code
     */
    const ENTITY_TYPE = 'blog-post';

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var PostUrlPathGenerator
     */
    protected $postUrlPathGenerator;

    /**
     * Store manager
     *
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var PostInterface
     */
    protected $post;

    /**
     * @param UrlRewriteFactory $urlRewriteFactory
     * @param PostUrlPathGenerator $postUrlPathGenerator
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        PostUrlPathGenerator $postUrlPathGenerator,
        StoreManagerInterface $storeManager
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->storeManager = $storeManager;
        $this->postUrlPathGenerator = $postUrlPathGenerator;
    }

    /**
     * @param PostInterface $post
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    public function generate($post)
    {
        $stores = $post->getStores();
        $this->post = $post;
        $urls = array_search(Store::DEFAULT_STORE_ID, $stores) === false ? $this->generateForSpecificStores($stores)
            : $this->generateForAllStores();
        $this->post = null;
        return $urls;
    }

    /**
     * Generate list of urls for default store
     *
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    protected function generateForAllStores()
    {
        $urls = [];
        foreach ($this->storeManager->getStores() as $store) {
            $urls[] = $this->createUrlRewrite($store->getStoreId());
        }
        return $urls;
    }

    /**
     * Generate list of urls per store
     *
     * @param int[] $storeIds
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    protected function generateForSpecificStores($storeIds)
    {
        $urls = [];
        $existingStores = $this->storeManager->getStores();
        foreach ($storeIds as $storeId) {
            if (!isset($existingStores[$storeId])) {
                continue;
            }
            $urls[] = $this->createUrlRewrite($storeId);
        }
        return $urls;
    }

    /**
     * Create url rewrite object
     *
     * @param int $storeId
     * @param int $redirectType
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite
     */
    protected function createUrlRewrite($storeId, $redirectType = 0)
    {
        return $this->urlRewriteFactory->create()->setStoreId($storeId)
            ->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($this->post->getId())
            ->setRequestPath(
                $this->postUrlPathGenerator->getUrlPathWithSuffixAndBlogRoute(
                    $this->post,
                    $storeId
                )
            )->setTargetPath($this->postUrlPathGenerator->getCanonicalUrlPath($this->post))
            ->setIsAutogenerated(1)
            ->setRedirectType($redirectType);
    }
}
